### PR TITLE
scoverage: Add console reporter

### PR DESCRIPTION
**Pull request by ramonmaruko**
Fixes lihaoyi/mill#763

This just outputs a coverage summary report. Useful for CI systems which don't support HTML/XML reports but have support for parsing stdout.

### CODE REVIEW

**Comment by lefou** [comment]
Unfortunately, travis-ci don't pass. But it looks like some travis specific hiccup. Have yon successfully ran the tests?

**Comment by ramonmaruko** [comment]
It's failing on some tests but I don't think it's related to my change. I am attaching the logs of running `ci/test-mill-0.sh`.

[test-mill-0-1.8.0_232.log](https://github.com/lihaoyi/mill/files/4120849/test-mill-0-1.8.0_232.log)
[test-mill-0-11.0.5.log](https://github.com/lihaoyi/mill/files/4120850/test-mill-0-11.0.5.log)

**Comment by lefou** [comment]
Most travis test succeeded. I restarted that one that failed with the typical envVars test and it failes now, but I think it is because master has new commits. So I'm merging (fingers crossed).

**Comment by ramonmaruko** [comment]
Thank you.

**Pull request merged**
