### PR TITLE
Add toMap and toJson methods to BuildInfo

### PR DESCRIPTION
**Pull request by sbly**
JSON is done via `ujson-circe` as this is what's already being used in the project itself

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
Mill uses upickle for JSON serialization. The circe version is probably only present for some contrib module.

**Comment by lihaoyi** [comment]
I don't think we should hardcode a ujson dependency in the BuildInfo modules. If anyone wants to convert it to JSON, calling `upickle.default.write(BuildInfo.toMap)` is trivial, and adding a ujson dependency bloats jars and leads to classpath conflicts

**Comment by lefou** [comment]
+1 for only adding the `toMap` method. But leaving out the `toJson`.
If you really need a out-of-the-box `toJson`, you could also pre-render it at generation time, as all values are constant anyway. This would add no extra dependencies.

**Comment by sbly** [comment]
@lihaoyi @lefou Thanks for the reviews! I removed the `toJson` method as recommended.

**Comment by lefou** [comment]
Thank you!

**Pull request merged**
