### PR TITLE
Upgrade scoverage: 1.3.1 -> 1.4.0

### PR DESCRIPTION
**Pull request by fabianhjr**

### CODE REVIEW

**Comment by fabianhjr** [comment]
Hi @lefou, I am a bit confused with the CI status.

Appveyor seems to work and one job of 9 failed on an unrelated test (with an empty env)

I have rebased and repushed the change so that Travis runs again and hopefully it will pass this time.

**Comment by lefou** [comment]
Yeah, some CI test fail sometimes on travis and AppVeyor currently don't run at all correct because of an outdated config. I already restarted the failed test on Travis but it failed with an git error. But your rebase action explains that now.

**Comment by lefou** [comment]
Thank you!

**Comment by fabianhjr** [comment]
Be welcome, thanks for maintaining mill. ^_^

**Pull request merged**
