### PR TITLE
Bump flyway version

### PR DESCRIPTION
**Pull request by kag0**

### CODE REVIEW

**Comment by kag0** [comment]
Is there something I should be doing to make appveyor pass?

**Comment by lihaoyi-databricks** [comment]
I think appveyor is just borked these days, feel free to ignore it for now

**Comment by lefou** [comment]
Out of curiosity, why is that custom logger needed?

**Comment by kag0** [comment]
The old version had a stdout logger available for us to import in flyway core. The new version has moved that logger into flyway command line and into private scope. So just adding it ourselves prevents us from having to add another dependency and needing to make some classes outside our package namespace.

**Pull request merged**
