### PR TITLE
Upgrade and fix bloop integration

### PR DESCRIPTION
**Pull request by jodersky**
This builds on top of #752 (thanks @krotton), mainly adding upickle serializers for the bloop config task (as suggested by @Baccata).

I tested it locally, and witth scalameta/metals-vscode#175 also fixed, bloop once again works out-of-the-box for mill projects!

### CODE REVIEW

**Comment by Baccata** [comment]
Looks great, many thanks @jodersky !

**Comment by jodersky** [comment]
@lihaoyi or @lefou, would it be possible to create an official release, now that this fix is in?

**Comment by Baccata** [comment]
@jodersky mill gets released for each merge to master. You should be able to set your mill version to `0.5.9-6-484657` and get these changes

**Comment by jodersky** [comment]
Good to know, thanks!

**Comment by lefou** [comment]
http://www.lihaoyi.com/mill/#overriding-mill-versions

**Pull request merged**
