### PR TITLE
Update utest to 0.7.6 on Scala Native tests

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Review by lefou — COMMENTED** [review]
Can we bump `Deps.utest` instead and use it here, too?

**Comment by lolgab** [comment]
@lefou Can a test share values with the build?
Can you point to an example? I have no idea on how to do this.

**Comment by lefou** [comment]
My bad. My initial though was to bump all usages of utest in mill and then I must have overlooked  that your diff doesn't touch the `build.sc`. I'm going to merge this PR.

**Comment by lefou** [comment]
Also, scala-steward already opened a PR for utest upgrade. #1119

**Pull request merged**
