### PR TITLE
Fixes for non-interactive (client/server) mode on Java 9

### PR DESCRIPTION
**Pull request by robby-phd**
More fixes for #156.

### CODE REVIEW

**Comment by robby-phd** [comment]
This can be updated when a new ammonite "unstable" is published after merging lihaoyi/ammonite#769.

**Comment by robby-phd** [comment]
Also for #224.

**Comment by rockjam** [comment]
looks good to me, @lihaoyi what do you think?

**Comment by robby-phd** [comment]
After this is merged, let's change `ci/test-mill-0.sh` to use non-interactive mode in order to test it on travis Java 9. 

I can create another pull request (or someone that has commit access to master can make that change directly) after a new mill release build is published.

**Comment by lihaoyi** [comment]
@rockjam no idea, if it looks good to you it looks good to me I guess

**Comment by lihaoyi** [comment]
@robby-phd I gave you commit access to the repo; you can merge this whenever you're ready. Also feel free to fix things on your own and merge other's PRs, though for big changes that need discussion let's still go through a code review.

**Comment by robby-phd** [comment]
@lihaoyi OK, thanks. I'd definitely want someone to review (non-trivial) changes.

**Pull request merged**
