### PR TITLE
Add "xsbti" as a shared prefix of the Scala compiler class loader

### LINKED ISSUE #1018: The ScalaInstance loader of Scala 3 is incompatible with the Zinc loader
The Scala 3 compiler depends directly on `org.scala-sbt:compiler-interface`, the Zinc interface.
Mill also depends on Zinc.

This is problematic because the `xsbti.*` classes can be loaded twice, the first time by the Mill class loader and the second time by the `ScalaInstance` class loader. It ends up with `LinkageException`.

So far the solution was to deconstruct the Zinc class loader and the underlying `ScalaInstance.loader` in the Scala 3 compiler bridge. But this is a very hacky and fragile solution ([see code here](https://github.com/lampepfl/dotty/blob/master/sbt-bridge/src/xsbt/CompilerClassLoader.java))

A better alternative would be to build a `scalaInstance.loader` in Mill ([current implementation here](https://github.com/lihaoyi/mill/blob/aa3240a52a72cfa5fe76c4d4c747f7f61eef2f1d/scalalib/worker/src/ZincWorkerImpl.scala#L309-L321)) that is compatible with the Zinc loader.

### PR DESCRIPTION
**Pull request by adpi2**
Fixes #1018

### CODE REVIEW

**Comment by adpi2** [comment]
@lihaoyi Could you review this pull request?

Here is the context: I want to remove the messy [CompilerClassLoader](https://github.com/lampepfl/dotty/blob/master/sbt-bridge/src/xsbt/CompilerClassLoader.java) in the Scala 3 bridge with Zinc. But if I do so I would break all Mill projects in the `community-build`. So my plan is:
- fix the Scala 3 loader in Mill
- release Mill
- update the Scala 3 community build projects
- fix the Scala 3 loader in `sbt-dotty` (https://github.com/lampepfl/dotty/pull/10541)
- remove the `CompilerClassLoader`

**Comment by adpi2** [comment]
This is ready for review! @lefou @lihaoyi could you have a look at it?

**Review by lefou — COMMENTED** [review]
Sorry for my late review. My only concern about this was, that we probably can't handle incompatible versions of the xsbti. But if I now understand correctly, we only share it with the classloader of the zinc worker, not with mills main classloader. So, this looks reasonable to me.

Just one minor thing. I'd like to keep non-wildcard imports were possible.

**Comment by adpi2** [comment]
> But if I now understand correctly, we only share it with the classloader of the zinc worker, not with mills main classloader.

Yes, exactly, we share the `xsbti` classloader with the Zinc worker which contains the zinc compiler bridge and the Scala compiler. This was not necessary before because the Scala 2 compiler does not depend on `org.scala-sbt:compiler-interface` (aka `xsbti`). But the dependency is inverted in Scala 3 and it is crucial that all the `xsbti` classes are loaded from the same loader.

**Comment by adpi2** [comment]
I pushed a fix for the wildcard import.

I don't know why the CI is stuck but I don't think it's related to this specific PR.

**Review by lefou — APPROVED** [review]

**Comment by lefou** [comment]
Thank you!

**Comment by adpi2** [comment]
Thank you @lefou for merging this. Since I want to follow this in lampepfl/dotty#10541 I'd like to know what the schedule for the next release.

**Comment by lefou** [comment]
You can already start to use it. Its version is `0.9.3-21-002361`. I think we will also tag a new release later this month, depending on how fast we can merge the open PRs.

**Pull request merged**
