### PR TITLE
Adds envVars propagation client -> server

### PR DESCRIPTION
**Pull request by Baccata**
Since Mill now executes in a long-lived JVM, the builds do not have a chance to use environment variables as inputs (ie `System.getEnv` returns the same result across several runs). 

This PR allows to propagate the environment variables from the client all the way down to the context and makes them available as a `Map[String, String]` so that they can be used as inputs should the user choose to do so.

Example of usage : 

`def envVar = T.input { T.ctx().env.get("ENV_VAR") } `

https://github.com/lihaoyi/mill/issues/257

- [x] Tests 

- [x] Documentation

### CODE REVIEW

**Comment by lihaoyi** [comment]
@robby-phd @rockjam one of you want to help review this?

**Comment by rockjam** [comment]
@lihaoyi will take a look

**Comment by rockjam** [comment]
@Baccata thank you, overall looks good. 
Can we have a test at `ClientServerTests` that env variables are actually passed to server, and also add doc section about prefered way to get env variable in build? (on this page I guess http://www.lihaoyi.com/mill/page/configuring-mill.html)

**Comment by Baccata** [comment]
Thanks for the feedback, I'll get on adding tests/doc asap

**Comment by Baccata** [comment]
@rockjam, for consistency I added documentation there : https://github.com/lihaoyi/mill/pull/267/files#diff-521aff6dd9f50dbf1ce6d38d8940bdd1R191. Hope that's okay. 

Also added a test

**Comment by rockjam** [comment]
@Baccata great that you find a good place to put it in docs. I'll take a closer look at PR when I have time.

**Comment by rockjam** [comment]
@Baccata There are some conflicts, can you take a look, will merge after that.

**Comment by rockjam** [comment]
@lihaoyi thank you

**Comment by Baccata** [comment]
@rockjam, sorry, was travelling all day yesterday, didn't see this until now. Thanks @lihaoyi !

**Pull request merged**
