### PR TITLE
Fix Sonatype requests retrying too fast

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Comment by lefou** [comment]
In essence, we just wait a bit longer each time after a previous 5xx error?

**Comment by joan38** [comment]
Yes exponentially.
Sonatype is sometimes taking time to commit the fact that a repo is closed. The issue could have been also resolved by waiting more between retries or by increasing the number of retries but I thought I'll make a proper exponential backoff to account for all situations.

**Comment by lefou** [comment]
Make sense. Thank you!

**Comment by joan38** [comment]
Do I need any more action on this wrt CI?

**Comment by joan38** [comment]
Great Thanks

**Pull request merged**
