### PR TITLE
universal script generation for assembly, launcher, and release that run on linux and windows

### PR DESCRIPTION
**Pull request by LolHens**
As a follow-up to lihaoyi/Ammonite#781 this pr generates scripts that can run on linux shell and windows cmd.
It merges the shell and batch scripts introduced in #243.
Feedback is always welcome!

### CODE REVIEW

**Comment by LolHens** [comment]
The error you are running into indeed seems very strange. I ran the version I just pushed on my windows system and on a redhat linux machine and it worked fine.
I had to change the approach because before I was prepending a "::" to every line of the shell script so that the cmd skips them however this does not work at all for switch case statements. The new approach tells the cmd to just jump over the shell script and should work for any script.
I removed the releaseAll and releaseBatch and now uploadToGithub only generates "mill".
Also I set the shebang line to be off by default.
Now I am just waiting to see what the tests will say :)

**Comment by LolHens** [comment]
Unfortunately I don't have access to that machine right now so I ran the tests on a local debian installation but I couldn't get all of the tests to succeed there.
I made a new commit but changed nothing just to restart the build and it seems to have worked where it previously failed at publishVersion in build.sc:360.
I think there might be some other bug involved that is not related to this pr.
Could you try again to execute the generated scripts?

**Comment by robby-phd** [comment]
I just tried it again locally on macOS and linux, and tests passed (didn't clean out `~/.mill` before). The changes look good to me, thanks.

**Comment by LolHens** [comment]
Very nice, thanks! Should I make a pr to change the generated script in ammonite according to this so that the code is equivalent?

**Comment by robby-phd** [comment]
That would be great!

**Comment by lihaoyi** [comment]
Oh ok, got it

**Pull request merged**
