### PR TITLE
Add AWS Codeartifact contrib module

### PR DESCRIPTION
**Pull request by realbrianstern**
This allows Mill projects to deploy to AWS Codeartifact. It functions similarly to the Artifactory PublishModule. Its credentials value is a Codeartifact auth token.

### CODE REVIEW

**Review by lefou — CHANGES_REQUESTED** [review]
What's missing here is the actual inclusion of the `codeartifact` module in the `build.sc`.

**Comment by realbrianstern** [comment]
Ah of course! Just added it

**Review by lefou — APPROVED** [review]
Looks good to me.

**Comment by lefou** [comment]
Thank you for this contribution!

**Pull request merged**
