### PR TITLE
Added ivyWhatDependsOn command

### LINKED ISSUE #250: add `ivyWhatDependsOn` command
Hi!

I've added `reverseTree` capabilities to coursier and I want to add `ivyWhatDependsOn "module"` command, but I'm not sure where to start to upgrade the version of coursier to 1.0.3 (already published to maven).

Thanks.

### PR DESCRIPTION
**Pull request by shanielh**
Fixes #250

### CODE REVIEW

**Comment by francisdb** [comment]
Why that Ivy prefix?

**Comment by martin-g** [comment]
Tests are missing!

**Comment by shanielh** [comment]
@francisdb I figured it will be easier to find with the prefix since the `ivyDepsTree` command...
@martin-g You're right, I'll add them, do you have some documentation on adding tests?

**Comment by francisdb** [comment]
That's also unfortunate naming. Ivy is not even in use.

**Comment by lihaoyi** [comment]
@shanielh looks ok to me; for the sake of the git history, can you flesh out the PR description with example input/output so I can see how this command is used?

**Comment by lihaoyi** [comment]
Closing due to inactivity

**Pull request closed without merging**
