### PR TITLE
can skip doc and src jars publish

### PR DESCRIPTION
**Pull request by shengc**

### CODE REVIEW

**Comment by lihaoyi** [comment]
Could this be a flag on `publishLocal` instead?

**Comment by shengc** [comment]
Yes I will tweak the PR tonight.

**Comment by shengc** [comment]
@lihaoyi does it look good to you now ?

**Comment by lihaoyi** [comment]
weren't you going to make it be a flag on `publishLocal` rather than their own, separate targets?

**Comment by shengc** [comment]
Is it a hiccup ? ci build was fine.

**Comment by lihaoyi** [comment]
kicked the ci build and it failed with the same output

**Comment by shengc** [comment]
it passed build on `travis-ci`, `cygwin` and `mysys2` , but failed on windows shell. This is where the trace reports what is broken with the PR introduced,
https://github.com/shengc/mill/blob/master/core/src/mill/define/Module.scala#L67

I don't have a windows machine to debug this. From the surface value of the error, it is not clear how the error could happen.

**Comment by lihaoyi** [comment]
Neither do I; perhaps you can add printlns and iterate on travis?

**Comment by robby-phd** [comment]
I previously encountered a similar exception under Java 9; try adding the following line after default's publishLocal:

```cmd
rd /s /q %USERPROFILE%\.mill &&
```

**Comment by lihaoyi** [comment]
closing due to inactivity

**Pull request closed without merging**
