### PR TITLE
[WIP] Basic CI infrastructure

### PR DESCRIPTION
**Pull request by piotrkwiecinski**
Refs: #16

### CODE REVIEW

**Comment by piotrkwiecinski** [comment]
For now https://github.com/lihaoyi/mill/blob/master/scalalib/src/test/scala/mill/scalalib/HelloWorldTests.scala#L295:L311 this fails as there is no ```scala``` binary. At least in the path.

It's possible to curl / wget ```.tgz``` and extract to dir X, add that dir to ```PATH```. We could use scala env var to get particular version of binary and add dir X to cache.

Thoughts? @rockjam, @lihaoyi 

Just in case I have it enabled on my fork: https://travis-ci.org/piotrkwiecinski/mill for overview.

**Comment by rockjam** [comment]
> https://github.com/lihaoyi/mill/blob/master/scalalib/src/test/scala/mill/scalalib/HelloWorldTests.scala#L295:L311 this fails as there is no scala binary. At least in the path.

I think we should not rely on `scala` command here. It wasn't a good solution anyway. We probably should run `java` and provide scala-library from build classpath. You can get it by evaluating `runDepClasspath` task. Also, you can use `mill.modules.Jvm.subprocess`

**Comment by lihaoyi** [comment]
I turned on Travis CI for the lihaoyi/mill repo; that means it should start building PRs like this one right?

I think a reasonable alternative would be to make the `runJar` test build an assembly and run that, instead of the `jar`. That should be self-contained, and include it's own Scala-library classpath right?

**Comment by piotrkwiecinski** [comment]
It's triggered. I'll have time to continue work within couple of hours.

**Comment by rockjam** [comment]
@piotrkwiecinski is there something that I can help with to finish this?

**Comment by dos65** [comment]
What about to fix tests right after merge? It looks good and maybe there will be problems with other tests that were added after branching. I'm looking forward to seeing green pr's )

**Comment by rockjam** [comment]
I agree. We could fix tests in separate PR's

**Comment by lihaoyi** [comment]
vadim/nikolay feel free to merge then if you think it looks good

**Pull request merged**
