### PR TITLE
Discover - break overridesRoutes into fixed size chunks

### PR DESCRIPTION
**Pull request by kongo2002**
I now did try to tackle #508 - as I said before I have not too much experience in scala macros so there might be a much nicer solution to this problem.

However this change successfully builds the example I posted before.

### CODE REVIEW

**Comment by kongo2002** [comment]
The added `LargeProjectTests` fails without the fix and succeeds afterwards. I hope I put it in the right place there :)

**Comment by lihaoyi** [comment]
@kongo2002 looks good. One more thing: could you try running the test without `Ydelambdafy=inline` and see if anything breaks?

**Comment by kongo2002** [comment]
Yes, it does work even without the `Ydelambdafy=inline` - I removed this from the test as well.

**Comment by lihaoyi** [comment]
looks good, thanks!

**Pull request merged**
