### PR TITLE
Future-proof isDotty check

### PR DESCRIPTION
**Pull request by smarter**
Same change I made against zinc: https://github.com/sbt/zinc/pull/678

### CODE REVIEW

**Comment by smarter** [comment]
This is incomplete, the dotty version regexp need to be updated too

**Comment by lihaoyi-databricks** [comment]
oh ok

**Comment by smarter** [comment]
Should be good to go now.

**Comment by lihaoyi** [comment]
@smarter CI seems red with a legitimate/related failure

**Comment by smarter** [comment]
Fixed.

**Pull request merged**
