### PR TITLE
Bumped Scala version to 2.12.10.

### PR DESCRIPTION
**Pull request by heksesang**

### CODE REVIEW

**Comment by lefou** [comment]
Why do we not immediately bump to 2.12.11?

**Comment by heksesang** [comment]
Ammonite is not published for it yet

**Comment by lefou** [comment]
There is a open pull request for Scala 2.12.11 in ammonite: https://github.com/lihaoyi/Ammonite/pull/1041

**Comment by heksesang** [comment]
Well, then the choice is to either wait until that pull request is merged and then bump to 2.12.11, or we bump it to 2.12.10 now and then 2.12.11 later.

**Comment by lefou** [comment]
Merging this one now.

@heksesang you said, mill does not work with Java 13? Can you open a ticket and link it to the ammonite ticket mentioned above? Thanks.

**Pull request merged**
