### PR TITLE
revive #254 and fix #268

### LINKED ISSUE #268: Mill after 0.1.7-8-b913c6 cannot build itself properly
Stumbled upon this when working on #262 so documenting it as an issue: changes between 0.1.7-8-b913c6 and 0.1.7-19-680364 cause mill not to be able to build itself properly; the resulting mill gives the following error trace when compiling itself:

```
mill.scalalib.ScalaWorkerModule.worker java.lang.NoClassDefFoundError: sbt/internal/inc/CompileFailed
    java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
    java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3110)
    java.base/java.lang.Class.getConstructor0(Class.java:3315)
    java.base/java.lang.Class.getConstructor(Class.java:2108)
    mill.scalalib.ScalaWorkerModule.$anonfun$worker$2(ScalaWorkerApi.scala:43)
```

See the [test-up](https://github.com/lihaoyi/mill/commits/test-up) branch's [appveyor](https://ci.appveyor.com/project/lihaoyi/mill/build/1.0.220) and [travis](https://travis-ci.org/lihaoyi/mill/builds/359615480) runs.

### PR DESCRIPTION
**Pull request by shengc**

### CODE REVIEW

**Comment by rockjam** [comment]
@shengc I think that diff is much bigger than intended, right? There are a lot of commits from other people in this PR

**Comment by shengc** [comment]
@rockjam I don't know how this can be properly handled. I just reverted the following and applied fix on top of it... 

commit 9b13e2b5a9ed6bc38e2ec173376556db5d71c05c
Author: Li Haoyi <haoyi.sg@gmail.com>
Date:   Sun Apr 1 23:01:42 2018 -0700

    revert #254 to fix bootstrapping https://github.com/lihaoyi/mill/issues/268

**Comment by rockjam** [comment]
@shengc you could try to `cherry-pick` required commit, or make a `format-patch` from it and apply to current master branch

**Comment by shengc** [comment]
@rockjam I have rebased the commits.

**Comment by rockjam** [comment]
Thank you. Can you point what is the fix exactly?

**Comment by shengc** [comment]
the `conf` part for `<dependency />` of generated `ivy.xml` was wrong. I just need to use `scopeToConf` function to convert `Scope` to its properly corresponding `configuration`.

**Comment by shengc** [comment]
@robby-phd @rockjam @lihaoyi the fix has passed the bootstrap test `test-mill-release.sh`

**Comment by rockjam** [comment]
Looks good to me

**Pull request merged**
