### PR TITLE
Revert Zinc to 1.2.5 to match release notes

### PR DESCRIPTION
**Pull request by ahirreddy**
Zinc was previously on on pre-release milestone (1.3.0-M1)

### CODE REVIEW

**Comment by lefou** [comment]
@lihaoyi , do you have any reason against this? (You bumped the version.) I have not tried all corner cases, but tests suceed. I'm in favour of merging this one, as it also fixed the out-of-sync relation to `Versions.scala`.

**Comment by lihaoyi** [comment]
@lefou this was an experiment to try and minimize some nondeterministic crashes in our Bazel build, which re-uses Mill's ZincWorkerImpl. Unfortunately, I don't think reverting the Zinc version solved it, so we can probably close this. @ahirreddy is that right?

**Comment by lefou** [comment]
Hm, either we merge or we fix the Changelog entry and the value of `Versions.zinc` to the currently used zinc version.

**Comment by vitaliis** [comment]
Had a question as well, why they are out of sync... :+1: for adjusting this.

**Comment by lihaoyi** [comment]
The original motivation for trying to get on the 1.3.0-Mx series was to see if Zinc's new compile-to-jar functionality works, since it could save us time zipping stuff into jars.

Turns out it doesn't haha

**Comment by lefou** [comment]
Ok then, I'll merge it.

**Comment by lefou** [comment]
@ahirreddy Thank you.

**Pull request merged**
