### PR TITLE
Support for webpack in Scala.js modules (issue #410)

### PR DESCRIPTION
**Pull request by pstutz**
I picked up the previous work from PR #437 (issue #410), which was closed due to inactivity, and tried to address the comments. I'm new to both webpack and mill and would appreciate it if someone with more experience could give me some guidance.

### CODE REVIEW

**Comment by pstutz** [comment]
I created an [example project](https://github.com/pstutz/scala-fullstack) that uses the same code to resolve nom dependencies.

**Comment by pstutz** [comment]
Usage example: https://github.com/pstutz/scala-fullstack

**Comment by atooni** [comment]
First of all, thanks for your work. I have recently migrated our own ScalaJS UI project to mill and in the end have decided *not* to include the configuration for webpack in the build.sc, but use mill as a driver for the JS tools only. To me that gave some more flexibility using the JS toolchain. 
I am not webpack specialist myself, so that comment is just from my limited experience. I need to finish another task, but then I could try to take some time and try our own project with your new module.

**Comment by pstutz** [comment]
@lefou Thanks, I'll start working on the documentation.

**Comment by pstutz** [comment]
@atooni Thanks a lot. I'm not satisfied with the current support for complex custom webpack.config.js use cases, so I'd be happy to extend and modify the approach based on your feedback.

**Comment by pstutz** [comment]
@lefou & @atooni: I added documentation and there is now support for using multiple custom webpack configs. Please let me know what you think.

**Comment by pstutz** [comment]
@atooni : "we are using a quite complex webpack config in order to limit the sizes of the individual js chunks that are being served." I assume that means multiple entry points and generated bundles?

**Comment by Visbone** [comment]
Why was this closed?

**Comment by pstutz** [comment]
Hi @Visbone, I wasn't able to get it working as quickly and as well as I as hoping. Personally I went back to using existing alternative tooling. I'm still excited about Mill and would love to have better support for full-stack projects with npm dependencies, but right now it would take more time to research/build it than can commit.

**Comment by Visbone** [comment]
Ah, makes sense. What you did so far is great tho imo, I'm using the webpack.sc from the fullstack project and it works like a charm. I prefer it over scalajsbundler. It doesn't work on windows because of npm, but I loved it so much I got WSL working. I have a friend that knows alot about webpack, but he is bogged down with coursework at the moment. Maybe when he is done maybe I can get him to take a look at this.

**Comment by pstutz** [comment]
@Visbone I'm glad it's useful for you, thanks for the kind words. :) I would be happy if someone picked it up. I was working on continuously running webpack with a worker in watch mode, but I struggled to find an elegant approach and ran out of patience.

**Pull request closed without merging**
