### PR TITLE
Testng integration test, that covers #553

### PR DESCRIPTION
**Pull request by lefou**
Contains #563

### CODE REVIEW

**Comment by lefou** [comment]
Travis failed with script `ci/test-mill-release.sh` with the following error:
```
1 targets failed
caffeine.test.compileClasspath 
Resolution failed for 1 modules:
--------------------------------------------
  com.lihaoyi:mill-contrib-testng:0.3.6-46-32c4a1 
	not found: /home/travis/.ivy2/local/com.lihaoyi/mill-contrib-testng/0.3.6-46-32c4a1/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/com/lihaoyi/mill-contrib-testng/0.3.6-46-32c4a1/mill-contrib-testng-0.3.6-46-32c4a1.pom
	not found: https://oss.sonatype.org/content/repositories/releases/com/lihaoyi/mill-contrib-testng/0.3.6-46-32c4a1/mill-contrib-testng-0.3.6-46-32c4a1.pom
	not found: https://dl.bintray.com/sbt/sbt-plugin-releases/com.lihaoyi/mill-contrib-testng/0.3.6-46-32c4a1/ivys/ivy.xml
	not found: https://jcenter.bintray.com/com/lihaoyi/mill-contrib-testng/0.3.6-46-32c4a1/mill-contrib-testng-0.3.6-46-32c4a1.pom
	not found: https://jitpack.io/com/lihaoyi/mill-contrib-testng/0.3.6-46-32c4a1/mill-contrib-testng-0.3.6-46-32c4a1.pom
	not found: http://repo.spring.io/plugins-release/com/lihaoyi/mill-contrib-testng/0.3.6-46-32c4a1/mill-contrib-testng-0.3.6-46-32c4a1.pom
X mill.integration.local.CaffeineTests.test 64488ms 
  utest.AssertionError: assert(eval("caffeine.test.compile"))
    utest.asserts.Asserts$.assertImpl(Asserts.scala:114)
    mill.integration.CaffeineTests.$anonfun$tests$2(CaffeineTests.scala:12)
1 targets failed
integration.test.test mill.integration.local.CaffeineTests mill.integration.local.CaffeineTests.test
The command "$CI_SCRIPT" exited with 1.
```

**Comment by lefou** [comment]
@lihaoyi Do you have an idea what's missing to fix the above Caffeine integration tests?

**Comment by lihaoyi** [comment]
no idea, maybe they're just flaky? They've been unreliable in the past. If it's a consistent failure, you'll have to figure it out

**Comment by lefou** [comment]
Finally, with the new CI environment, these test pass as epected and this PR is good to go. Also thanks to @jeantil initial work.

I'll squash as appropriate and merge.

**Pull request merged**
