### PR TITLE
Add flatMap on Result

### PR DESCRIPTION
**Pull request by joan38**
This is needed for example [here](https://github.com/joan38/mill-scalafix/blob/master/mill-scalafix/src/com/goyeau/mill/scalafix/ScalafixModule.scala#L35-L51) where I [patched it how I can](https://github.com/joan38/mill-scalafix/blob/master/mill-scalafix/src/com/goyeau/mill/scalafix/ScalafixModule.scala#L22-L28)

### CODE REVIEW

**Comment by joan38** [comment]
@lefou Can I get review on this?

**Comment by lefou** [comment]
Sure, I already had a look but honestly have no idea if a `flatMap` introduce any issues conceptually? It looks good to me though.

@lihaoyi, WDYT?

**Comment by joan38** [comment]
It's really to be able to chain them possibly in a for comprehension.
I don't see how to use this type if I can't chain them really. See [the usage example](https://github.com/joan38/mill-scalafix/blob/master/mill-scalafix/src/com/goyeau/mill/scalafix/ScalafixModule.scala#L35-L51).

**Comment by lihaoyi** [comment]
No idea, seems handy

**Pull request merged**
