### PR TITLE
[WIP] Docs, readme.md, ci updates once 0.1.8 is released

### PR DESCRIPTION
**Pull request by robby-phd**
Tasks: 

- [ ] Prerequisite: release 0.1.8
- [ ] Update changelog in readme.md to include more changes, if any
- [ ] Update .travis.yml to use 0.1.8
- [ ] Update .appveyor.yml to use 0.1.8

### CODE REVIEW

**Comment by lihaoyi** [comment]
@robby-phd 0.1.7 is tagged https://github.com/lihaoyi/mill/commit/4b0350f868581c7ec0e1307bb6fea516a46e7e8b, should publish itself to github-releases/maven-central once it passes tests

**Comment by lihaoyi** [comment]
@robby-phd the java 9 build seems to be sad after bumping the version of Ammonite to 1.1.0 

https://travis-ci.org/lihaoyi/mill/jobs/358243055#L479

Any idea what's up?

**Comment by robby-phd** [comment]
@lihaoyi I created lihaoyi/Ammonite#779. 

Now, when I build mill on my machine (mac), I got the same error as in [AppVeyor when you bumped up Ammonite and upickle](https://ci.appveyor.com/project/lihaoyi/mill/build/1.0.170/job/dyiv69lfelie6hg3) (I had to comment out some lines in my local copies of build.sc and upload.sc to test lihaoyi/Ammonite#779 with mill in my machine).

**Comment by robby-phd** [comment]
Changes have been made directly in `master` (and `0.2.0`), so closing this one.

**Pull request closed without merging**
