### PR TITLE
Dottydoc fix

### PR DESCRIPTION
**Pull request by heksesang**
Fix for #785, adds support for dottydoc in `ScalaModule.docJar`.

### CODE REVIEW

**Comment by smarter** [comment]
Looks fine to me but it's missing tests.

**Comment by lefou** [comment]
@smarter Thanks for your review.

@heksesang Do you intend to add a test case covering the dottydoc generation?

Besides, this branch has one merge conflict.

**Comment by heksesang** [comment]
Yeah, I was thinking I'll add test cases once I have time for it.

**Comment by lefou** [comment]
bump

**Comment by heksesang** [comment]
Can close this now that #904 implements this.

**Pull request closed without merging**
