### PR TITLE
support ZIO code gen  -   #789

### PR DESCRIPTION
**Pull request by DamianReeves**

### CODE REVIEW

**Comment by lefou** [comment]
Can you also update the documentation and tests?

**Comment by DamianReeves** [comment]
Sure. I seem to be having issues getting the tests to all pass locally, even if I remove all my changes (i.e. running master).

**Comment by lefou** [comment]
Just make sure, that `mill contrib.scalapblib.__.test.test` passes.

**Comment by lefou** [comment]
@DamianReeves Are you still stuck on executing tests? If I can help you anyhow, just ping me on Gitter.

**Comment by DamianReeves** [comment]
I stepped away from this for a bit, but I'm expecting to be able to get back to it by next weekend

**Pull request closed without merging**
