### PR TITLE
Fix Scala.js 1.x where x != 0

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by lefou** [comment]
Thank you very much. I think our growing mill community is appreciating Scala.js 1.1 support. Do we have a test case that ensures, our setup works for Scala.js 1.0 as well as 1.1?

**Comment by lolgab** [comment]
Ready for another review round :)

**Comment by lolgab** [comment]
The failure in Travis seems unrelated.

**Comment by lolgab** [comment]
Thank you for merging! 🎉

**Pull request merged**
